config/routes.rb
require 'resque/server'

G5SiblingDeployer::Application.routes.draw do
  mount G5Ops::Engine => '/g5_ops'
  mount Resque::Server, :at => "/resque"
  root to: "siblings#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper

  def app_display_name
    ENV["APP_DISPLAY_NAME"]
  end

  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

 def header_right(page_header_right, show_header_right = true)
    content_for(:header_right) { h(page_header_right.to_s) }
    @show_header_right = show_header_right
  end

  def show_header_right?
    @show_header_right
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end

  def flash_div(level)
    if flash[level].present?
      bootstrap_level = (level.to_s == "notice" ? "info" : level)
      content_tag "div", class: "alert alert-#{bootstrap_level}" do
        content_tag "p", flash[level]
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= app_display_name %> - <%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <meta charset="utf8" />
    <%= yield(:head) %>
  </head>
  <body>
    <div class="container-fluid">

      <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
          <div class="container">

            <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </a>

            <!-- Be sure to leave the brand out there if you want it shown -->
            <a class="brand" href="<%= root_path %>"><%= app_display_name %></a>

            <!-- Everything you want hidden at 940px or less, place within here -->
            <div class="nav-collapse">
              <ul class="nav">
                <li><%= link_to "Siblings", siblings_path %></li>
                <li><a href="/resque" target="_blank">Resque</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <% flash.each do |name, msg| %>
        <%= flash_div name %>
      <% end %>

      <div class="row-fluid page-header">
        <%= content_tag :h1, yield(:title), class: "span10" if show_title? %>
        <%= content_tag :span, yield(:header_right), class: "span2" if show_header_right? %>
      </div>

      <%= yield %>

    </div>
  </body>
</html>